generic-datatable/objects/Datatable_Column_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Column_API__c</fullName>
        <label>Column API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Column_Type__c</fullName>
        <label>Column Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>text</fullName>
                </value>
                <value>
                    <fullName>number</fullName>
                </value>
                <value>
                    <fullName>currency</fullName>
                </value>
                <value>
                    <fullName>date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Datatable_Object_Setting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Datatable Object Setting</label>
        <referenceTo>Datatable_Object_Setting__c</referenceTo>
        <relationshipLabel>Datatable Column Settings</relationshipLabel>
        <relationshipName>Datatable_Column_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieldName__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Object_API__c</fullName>
        <label>Parent Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Datatable Column Setting</label>
    <nameField>
        <label>Column Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatable Column Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

generic-datatable/unpackaged/objects/Datatable_Object_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Object_API__c</fullName>
        <label>Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Datatable Object Setting</label>
    <nameField>
        <label>Datatable Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatable Object Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

generic-datatable/unpackaged/classes/DatatableHelper.cls
public class DatatableHelper {
    public static set<Id> publishEventSet = new set<Id>();
    public static Datatable_Object_Setting__c DatatableSetting {get; set;}
    public static String QueryFilterString {get; set;}
    public static String QuerySortString {get; set;}
    
    public static void getSettings(String DataTableSettingId, String FilterString, String SortString){
        if(DatatableSetting == null){
            QueryFilterString = FilterString;
            QuerySortString = SortString;
            DatatableSetting = [Select Id, Name, Object_API__c, (Select Id, Name, Order__c, Column_API__c, Parent_Object_API__c, FieldName__c, Column_Type__c from Datatable_Column_Settings__r Order By Order__c ASC) from Datatable_Object_Setting__c where Id =:DataTableSettingId];
        }
    }
    
    public static String getData(){
        String query = getQuery();
        List<sObject> dataList = Database.query(query);
        
        String returnData = '';
        JSONGenerator gen = JSON.createGenerator(false);
        gen.writeStartArray();
        for(sObject data : dataList){
            gen.writeStartObject();
            for(Datatable_Column_Setting__c column : DatatableSetting.Datatable_Column_Settings__r){ 
                sObject target = data;
                if(!String.isBlank(column.Parent_Object_API__c)){
                    List<String> parents = column.Parent_Object_API__c.split('\\.');
                    for(String parent : parents){
                        target = target.getSobject(parent);
                    } 
                }
                
                String elementValue = target != null && target.get(column.Column_API__c) != null ? String.valueOf(target.get(column.Column_API__c)) : '';
                gen.writeStringField(column.FieldName__c, check(elementValue));
            }
            gen.writeEndObject();
        }
        gen.writeEndArray();
        returnData = gen.getAsString();
        return returnData;
    }
    
    public static String getColumns(){
        String returnCloumns = '';
        JSONGenerator gen = JSON.createGenerator(false);
        gen.writeStartArray();
        for(Datatable_Column_Setting__c column : DatatableSetting.Datatable_Column_Settings__r){
            gen.writeStartObject();
            gen.writeStringField('label', column.Name);
            gen.writeStringField('fieldName', column.FieldName__c);
            //gen.writeNumberField('initialWidth', 150);
            gen.writeStringField('type', column.Column_Type__c);
            gen.writeEndObject();
        }
        gen.writeEndArray();
        returnCloumns = gen.getAsString();
        
        return returnCloumns;
    }
    
    public static String check(String value){
        if(value == null){
            return '';
        }
        return value;
    }
    
    public static Decimal checkD(Decimal value){
        if(value == null){
            return 0;
        }
        return value;
    }
    
    public static string getQuery(){
        String queryString = '';
        queryString += 'SELECT Id, ';
        
        for(Datatable_Column_Setting__c column : DatatableSetting.Datatable_Column_Settings__r){
            if(String.isBlank(column.Parent_Object_API__c)){
                queryString += column.Column_API__c + ', ';
            }else{
                queryString += column.Parent_Object_API__c + '.' + column.Column_API__c + ', ';
            }
        }
        queryString = queryString.removeEnd(', ');
        
        queryString += ' FROM ' +  DatatableSetting.Object_API__c;
        
        if(!String.isBlank(QueryFilterString)){
            queryString += ' WHERE ' + QueryFilterString;
        }
        
        if(!String.isBlank(QuerySortString)){
            queryString += ' Order By ' + QuerySortString;
        }
        
        return queryString;
    }
}